# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Homelab Dashboard
theme: dark
color: slate
background:
  image: /images/Fantasy-Lanscape-Night.png
  blur: xs # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  opacity: 60 # 0-100
  brightness: 80

quicklaunch:
  searchDescriptions: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: custom
  url: "https://www.google.com/search?q="
  target: "_self"

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
