---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: [google, brave] # google, duckduckgo, bing, baidu, brave or custom
    focus: false # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _self # One of _self, _blank, _parent or _top

- datetime:
    text_size: xl
    format:
      timeStyle: short
